BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'UBLOG_USERS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ' || 'UBLOG_USERS_ID_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER ' || 'UBLOG_USERS_ID_TRG';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN
      RAISE;
    END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ' || 'UBLOG_POSTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ' || 'UBLOG_POSTS_ID_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER ' || 'UBLOG_POSTS_ID_TRG';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN
      RAISE;
    END IF;
END;
/
CREATE TABLE UBLOG_USERS (
    id NUMBER PRIMARY KEY,
    email_id VARCHAR2(100),
    password VARCHAR2(100)
);
/
CREATE SEQUENCE UBLOG_USERS_ID_SEQ;
/
CREATE TRIGGER UBLOG_USERS_ID_TRG
    BEFORE
    INSERT
    ON UBLOG_USERS
    FOR EACH ROW
BEGIN
    SELECT UBLOG_USERS_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
INSERT INTO UBLOG_USERS(email_id, password) VALUES ('admin@admin.com', 'admin');
/
CREATE TABLE UBLOG_POSTS (
    id NUMBER PRIMARY KEY,
    email_id VARCHAR2(100),
    title VARCHAR2(200),
    description VARCHAR2(1000),
    tag VARCHAR2(10),
    timestamp VARCHAR2(200)
);
/
CREATE SEQUENCE UBLOG_POSTS_ID_SEQ;
/
CREATE TRIGGER UBLOG_POSTS_ID_TRG
    BEFORE
    INSERT
    ON UBLOG_POSTS
    FOR EACH ROW
BEGIN
    SELECT UBLOG_POSTS_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
SELECT owner, table_name FROM all_tables WHERE TABLE_NAME = 'UBLOG_USERS' or TABLE_NAME = 'UBLOG_POSTS';
/